spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/testdb
    driver-class-name: org.h2.Driver
    username: '{cipher}AQBFJu3lLr4G3ZvAzTz0zLhVX07qcWto49Sos+8arpGXTMEIrptQeJkyDwW9jlBNcCtkTwkYnRfkmQFPL94I8HpS7ULzGlLo627ksoqah0KhFYjr+V29jRcf0ozK/HOKmY81Ru9dqqBGjzkAocH6ZLdY5KFt5bmCaz/AJ9cRw01kvhCkZAGgfZW45tBPczxwoKVbsgLH5LuwWCDRD/933OBtm4wYJtoGfrDbSdVRBDtkSfRAIa+fWe83mHJWPGT2N0ta0YojNekZRO9Fh2CjrZX3TVMwye3gnUEDG/dSJDUNrSrQMH3mGHn3rZk6nq/4NZ9dBA/8Ryqyt9H+GlbRbkcAGnPxDRBvklH3B1M44NQQIdYL/mzlOCVmAj12z18rYag='

token:
  expiration_time: 86400000
  secret: '{cipher}AQBmxOJbzuQj/OjHm+3gf9llHbijA+DYPR0uDaDLAN7eNhJ8wtJL72miHviTnxh9iN2JIDK0OiSSsmy4himT6UWGz58gJmR53F7YA89WAqiZm3u9VQEz3/XfGIE7AW4EtbhlgsgsZI7rGglGxPIgylBjg2sneeQ6w8JzPgORiMdayXFjtdEmeFkk5/pW3RwXxq/vCALQh+kPQDjMncybhtLqHXVPs2EKjPFl7XM+xIbKuUzEDYNxzJOwz/OQ6Ii4Bv1BjBr/XabvtP9HcBis7wCjQE/q/cNbIuNRnKRY+bTujxyfgSFTLEpylebqkuNLGau4SRenYY7W3sqaDOc+maTvwnAMTu0bnaGK0ZKXAyYO6lf01+V6uXGhdL001RHwYdN3JdfZ/4839gbvVfkIL/mRtYdaZZMDRazuiYP7Eq9BGj+C0+lNzVJkEOjmhE58NE0='

gateway:
  ip: 172.30.1.59

order_service:
  url: http://order-service/order-service/%s/orders